import XCTest
import Hub
import Tokenizers
@testable import DiffusionModel

final class LLaDA2MoeTokenizerTests: XCTestCase {
    
    struct TestFixture: Decodable {
        let type: String
        let text: String?
        let messages: [[String: String]]?
        let formattedText: String?
        let tokens: [Int]
        
        enum CodingKeys: String, CodingKey {
            case type
            case text
            case messages
            case formattedText = "formatted_text"
            case tokens
        }
    }
    
    func testTokenizerParity() async throws {
        // Load the 100-case reference fixtures generated by Python
        let fixturePath = "./scratch/tokenizer_test_fixtures.json"
        let fixtureURL = URL(fileURLWithPath: fixturePath)
        
        guard FileManager.default.fileExists(atPath: fixturePath) else {
            XCTFail("Fixture file not found at \(fixturePath). Please run generate_tokenizer_fixtures.py first.")
            return
        }
        
        let data = try Data(contentsOf: fixtureURL)
        let fixtures = try JSONDecoder().decode([TestFixture].self, from: data)
        
        XCTAssertEqual(fixtures.count, 100, "Fixtures JSON should contain exactly 100 test cases.")
        
        print("Loading DiffusionTokenizer from inclusionAI/LLaDA2.1-mini...")
        let tokenizer = try await DiffusionTokenizer.from(pretrained: "inclusionAI/LLaDA2.1-mini")
        
        // Assert special token IDs
        XCTAssertEqual(tokenizer.maskId, 156895)
        XCTAssertEqual(tokenizer.eosId, 156892)
        XCTAssertEqual(tokenizer.padId, 156892)
        
        // Verify each test case against Python references
        for (index, fixture) in fixtures.enumerated() {
            if fixture.type == "text" {
                guard let text = fixture.text else {
                    XCTFail("Text fixture \(index) is missing text.")
                    continue
                }
                
                // 1. Encode parity
                let encoded = tokenizer.encode(text: text)
                XCTAssertEqual(encoded, fixture.tokens, "Text encode mismatch at index \(index): '\(text)'")
                
                // 2. Decode parity
                let decoded = tokenizer.decode(tokens: fixture.tokens)
                // Normalize whitespaces/newlines/special tokens if needed, but swift-transformers
                // and Python transformers should yield the exact same round-trip decoded text.
                XCTAssertEqual(decoded, text, "Text decode mismatch at index \(index)")
                
            } else if fixture.type == "chat" {
                guard let messages = fixture.messages else {
                    XCTFail("Chat fixture \(index) is missing messages.")
                    continue
                }
                
                // 1. Apply Chat Template + Encode parity
                let encoded = try tokenizer.applyChatTemplate(messages: messages)
                XCTAssertEqual(encoded, fixture.tokens, "Chat template apply + encode mismatch at index \(index)")
                
                // 2. Decode parity check
                if let formattedText = fixture.formattedText {
                    let decoded = tokenizer.decode(tokens: fixture.tokens)
                    XCTAssertEqual(decoded, formattedText, "Chat decode mismatch at index \(index)")
                }
            }
        }
        
        print("Successfully verified tokenizer parity for all 100 test cases!")
    }
}
